// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRk-6l0nL4uYrnuStCb5oEs6NHIF-PEU',
    appId: '1:466847334457:web:0cc70a466f95fe748b8de8',
    messagingSenderId: '466847334457',
    projectId: 'outpos-client-paytab',
    authDomain: 'outpos-client-paytab.firebaseapp.com',
    storageBucket: 'outpos-client-paytab.firebasestorage.app',
    measurementId: 'G-DQ6G8KK8XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLMG7f9U3i0l5L_2zuM7oojAYbysN7Gk',
    appId: '1:466847334457:android:193616891da3247b8b8de8',
    messagingSenderId: '466847334457',
    projectId: 'outpos-client-paytab',
    storageBucket: 'outpos-client-paytab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4gl3Z-Vw4o6BD-98rBX4dQ83N1fDnRA',
    appId: '1:466847334457:ios:3ae0b8ebc2eac4728b8de8',
    messagingSenderId: '466847334457',
    projectId: 'outpos-client-paytab',
    storageBucket: 'outpos-client-paytab.firebasestorage.app',
    iosBundleId: 'kr.paytap.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4gl3Z-Vw4o6BD-98rBX4dQ83N1fDnRA',
    appId: '1:466847334457:ios:f8dbfd2cc76af2cd8b8de8',
    messagingSenderId: '466847334457',
    projectId: 'outpos-client-paytab',
    storageBucket: 'outpos-client-paytab.firebasestorage.app',
    iosBundleId: 'kr.paytap.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABRk-6l0nL4uYrnuStCb5oEs6NHIF-PEU',
    appId: '1:466847334457:web:3e5ca5829aaf31418b8de8',
    messagingSenderId: '466847334457',
    projectId: 'outpos-client-paytab',
    authDomain: 'outpos-client-paytab.firebaseapp.com',
    storageBucket: 'outpos-client-paytab.firebasestorage.app',
    measurementId: 'G-R1Q9TR2ZGQ',
  );
}
